{
 "title": "Celery Monitoring",
 "tags": [
  "prometheus",
  "celery"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(celery_tasks_total,namespace)"
   },
   {
    "name": "Name",
    "query": "label_values(celery_tasks_total,name)"
   },
   {
    "name": "State",
    "query": "label_values(celery_tasks_total,state)"
   },
   { "name": "Interval", "query": "30s,1m,5m,15m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Celery Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Celery Events by State rate (average $Interval)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( rate(celery_tasks_total{namespace=~\"^$Namespace$\",name=~\"^$Name$\",state=~\"^$State$\"}[5m])  ) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Celery Events by Tasks rate (average $Interval)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( rate( celery_tasks_total{namespace=~\"^$Namespace$\",name=~\"^$Name$\",state=~\"^$State$\"}[5m] ) ) by (name,state)",
     "legendFormat": "{{name}}/{{state}}"
    }
   ]
  },
  {
   "title": "Celery Tasks runtime rate (average $Interval)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum ( rate( celery_tasks_runtime_seconds_bucket{namespace=~\"^$Namespace$\",name=~\"^$Name$\"}[5m] ) ) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Celery Task latency rate (by $Interval)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum ( rate( celery_tasks_latency_seconds_bucket{namespace=~\"^$Namespace$\",name=~\"^$Name$\"}[5m] ) ) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Current Worker Count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(celery_workers{namespace=~\"^$Namespace$\"}[$Interval]))"
    }
   ]
  },
  {
   "title": "Top Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 15 Tasks $State",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "repeat": "State",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(15, sum( irate( celery_tasks_total{namespace=~\"^$Namespace$\",name=~\"^$Name$\",state=~\"$State\"}[1m] ) ) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}