{
 "title": "OWN metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Scrapping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrap_in_seconds_created" }
   ]
  },
  {
   "title": "preprocess in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "preprocess_in_seconds_created" }
   ]
  },
  {
   "title": "fetching requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fetching_requests_created" }
   ]
  },
  {
   "title": "preprocess requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "preprocess_request_created" }
   ]
  }
 ]
}