apiVersion: v1
kind: Service
metadata:
  name: {{ include "ownmetrics.fullname" . }}
  labels:
    {{- include "ownmetrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ownmetrics.service.type }}
  ports:
    - port: {{ .Values.ownmetrics.service.port }}
      targetPort: celery-exporter
      protocol: TCP
      name: http-metrics-celery-exporter
  selector:
    {{- include "ownmetrics.selectorLabels" . | nindent 4 }}
